### ISSUE TITLE
Multiple variants

### ISSUE THREAD

**Issue by caseykulm** [bitrise-steplib/bitrise-step-android-build#10]
I am looking to run both `release` and `releaseUnitTest`.

It looks like currently that this only supports 1 variant via [this line](https://github.com/bitrise-steplib/bitrise-step-android-build/blob/999995b85fff7f7ab9362135aa442114f9c73a7d/main.go#L102). 

Would it make sense to allow a comma delimited list of variants to support multiple variants for this one step?

**Comment by fehersanyi-bitrise** [comment]
Hello there, you should use the `gradle runner` step in that you can define assembleRelease assembleReleaseUnitTest` without any issues
<img width="912" alt="Screenshot 2019-04-26 at 10 07 10" src="https://user-images.githubusercontent.com/43136024/56792943-16ebec80-680b-11e9-8a05-5ce235ab251d.png">
