### ISSUE TITLE
issue with android test resources and manifest not found

### ISSUE THREAD

**Issue by dabitdev** [bitrise-steplib/bitrise-step-android-build#12]
Hi, I just updated from 0.9.5 to 0.10.0 to be able to use aab instead of apk. 
But the build is not working.
https://app.bitrise.io/build/8b3ea3109873e3b3#?tab=log

* What went wrong:
Execution failed for task ':app:bundleDevDebugAndroidTestResources'.
> Cannot find merged manifest file
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

**Comment by bitce** [comment]
Hi @dabitdev!

Based on [this thread](https://stackoverflow.com/questions/44087073/kotlin-on-android-cannot-find-main-merged-manifest-what-is-causing-this-error) seems like a Kotlin problem, have you checked this out already? Also is this non-reproducible with any other versions of the step?

**Comment by dabitdev** [comment]
hi @bitce thank you for taking your time on looking at this.
I decided to do the builds manually for now. I will go back to the deployment job later. 
I am closing the ticket.

**Comment by rubyboy** [comment]
@dabitdev we're having the same issue. Manual builds using the gradle runner work well (which is what we've resorted to a this point).
If I omit the ":app:bundleDebugAndroidTestResources" gradle task it works well. Is there a way to override the gradle tasks in this step, or maybe you can help understand why this is happening?
You can find our app here: https://app.bitrise.io/app/f64828986de0fdd1
Thanks.

**Comment by hadus07** [comment]
> If I omit the ":app:bundleDebugAndroidTestResources" gradle task it works well.

@rubyboy how did you manage to omit `:app:bundleDebugAndroidTestResources`?

**Comment by rubyboy** [comment]
> > If I omit the ":app:bundleDebugAndroidTestResources" gradle task it works well.
> 
> @rubyboy how did you manage to omit `:app:bundleDebugAndroidTestResources` task?

We've switched from the "Android Build" step to the more generic "Gradle Runner", where you can control the specific gradle tasks to run. When this bug is fixed, we'll switch back to the "Android Build".

![image](https://user-images.githubusercontent.com/1908166/67408608-f33f0e80-f5c1-11e9-9e06-a903e3e3a1bf.png)

**Comment by tstrijdhorst** [comment]
I'm having the same problem when trying to output AAB (APK works fine) on a react-native project. Any fix for this other than resorting to the gradle runner?

**Comment by GustavodeJesus** [comment]
I solved it as follows: Step **Android Build** -> Aditional Gradle Arguments -> -x ":app:bundleDebugAndroidTestResources"

**Comment by lpusok** [comment]
Hello @tstrijdhorst, @GustavodeJesus 
Specifying an explicit variant works around this issue. The only drawback is that only one variant can be specified at the moment.

**Comment by istvankovacs-bitrise** [comment]
This issue has been fixed with #18. Furthermore, it is now able to set multiple variants as well.
