### ISSUE TITLE
File exclude filter

### ISSUE THREAD

**Issue by deive** [bitrise-steplib/bitrise-step-android-build#22]
It would be very useful to have an exclude filter for the App artifact (.apk, .aab) location pattern so that we don't get all intermediate builds, such as the unsigned and test apps.
Gradle Runner has this with a default value of:
*unaligned.apk
*Test*.apk

This step is more simple than the gradle runner and is used by default, but without this setting I have had to revert to using that.

I have attempted to fork and PR this but I am not a go programmer and I can't get the tests running:
```
just git clone this repository, cd into it's folder in your Terminal/Command Line and call bitrise run test
```
results in (local path masked with [full_path])
```golint failed
cannot find package "_/Users/[full_path]/bitrise-step-android-build" in any of:
	/Users/deive/.bitrise/toolkits/go/inst/go/src/_/Users/[full_path]/bitrise-step-android-build (from $GOROOT)
	/Users/deive/go/src/_/Users/[full_path]/bitrise-step-android-build (from $GOPATH)
```

**Comment by chaitanyatanna-bitrise** [comment]
Hi @deive 
Thank you for reaching out to Bitrise.
Can you please enable Support User from your project settings and send us the build URL?

Thanks
Chaitanya

**Comment by deive** [comment]
Hi @chaitanyatanna-bitrise, thanks for looking! 
I have created a new Android app and a new build to show this and have turned on the Support User. The app is at https://app.bitrise.io/app/8217ee3683f31d9b#

The only addition is to copy the Android Build step from the deploy to the primary step which then archives the 2 extra APKs.

**Comment by chaitanyatanna-bitrise** [comment]
Hi @deive 
Thank you for the build URL.
I think the feature you are requesting is not available yet in the product.
Can you please explain to me the use case so that I can inform the feature to the product team?

Thanks
Chaitanya

**Comment by deive** [comment]
It is a new feature, yes.

The use case is to be able to produce a build (to output the app as an APK or AAB) and to archive that build (e.g. app-debug.apk), without archiving all other build artifacts that have been genereated (e.g. app-debug-androidTest.apk, app-debug-unsigned.apk, etc.)

I hope this explains what I am trying to do?

**Comment by chaitanyatanna-bitrise** [comment]
Hi @deive 
Thank you for the use case. This is very helpful.
I will let the product team of this new feature request.

Thank you 
Chaitanya

**Comment by deive** [comment]
I would say this is still important to me, the simpler default step would be nicer to use, but isn't really usable without the filter.

**Comment by mefiblogger** [comment]
Hello,

It's Mefi here from the Bitrise CoreSteps Team. Thanks for reaching out helping us and the mobile community to have a better experience with Bitrise steps. 💜

We started to have a broader review of all the open issues and PRs and we are continuously prioritizing these in our sprints.

We reviewed this issue and we found it to be a valid feature request. We are collecting new feature requests on our [Discuss forum](https://discuss.bitrise.io/c/feature-request/) where you can upvote and discuss further details. As this one is on our current roadmap, I close the issue and we'll share an update once we released the new version of the step. Until then, feel free to create a feature request and share your thoughts on Discuss.

Happy building! 🚀
