### ISSUE TITLE
Google Json - No matching client found for package name 

### ISSUE THREAD

**Issue by lukesteves92** [bitrise-steplib/bitrise-step-android-build#38]
Hi team, 

Good day!

So, i have added a new variant to my Android Project and my workflow was updated. 

Issue: Bitrise does not find the package name on my json, being that it is updated. All info are correct. The build of the other variants is executed 100%.

[apps_a176c6a678e6fe22_7565f94a-7143-4cd6-b5cc-cedf5c02f259-full.txt](https://github.com/bitrise-steplib/bitrise-step-android-build/files/8595006/apps_a176c6a678e6fe22_7565f94a-7143-4cd6-b5cc-cedf5c02f259-full.txt)

[bitriseyml.txt](https://github.com/bitrise-steplib/bitrise-step-android-build/files/8595010/bitriseyml.txt)

Could u help me, please?

Thanks!!!

**Comment by godrei** [comment]
Hi @lukesteves92 ,
The Step fails at the 8. Step (`android-build` - `Build - Deixa Comigo`), actually the executed gradle command (`/bitrise/src/gradlew ":app:assembleDeixacomigoDebug"`) fails.

Before this Step, there is a script Step, which seems to be responsible for downloading the `google-services.json` for the project.
This script has some suspicious logs:

```
/tmp/bitrise035159132/step_src/._script_cont: line 3: brew: command not found
/tmp/bitrise035159132/step_src/._script_cont: line 6: brew: command not found
```

Are you sure this script is working properly?

**Comment by lukesteves92** [comment]
My script:

git stash

if brew ls --versions jq > /dev/null; then
echo "The package is installed"
else
brew install jq
fi

google=$(curl -s -H 'domain-id: '13', Content-Type: application/json' $BASE_URL/$REMOTE_CONFIG_URL | jq '.android.domain.settings.firebase_config_android')
google="${google#\"}"
curl -o ./google-services.json -k $google

**Comment by godrei** [comment]
Hi @lukesteves92 ,
could you please add `cat ./google-services.json` to the end of the script, run a new build and check if the file content looks good?
