### ISSUE TITLE
Execution failed for task ':app:mergeReleaseNativeLibs'. > Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.    > Failed to transform ctos_print.jar to match attributes {artifactType=android-java-res, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.       > Execution failed for JetifyTransform: /bitrise/src/app/libs/ctos_print.jar.          > Transform's input file does not exist: /bitrise/src/app/libs/ctos_print.jar. (See https://issuetracker.google.com/issues/158753935)

### ISSUE THREAD

**Issue by abdelrahmana** [bitrise-steplib/bitrise-step-android-build#40]
Execution failed for task ':app:mergeReleaseNativeLibs'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Failed to transform ctos_print.jar to match attributes {artifactType=android-java-res, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /bitrise/src/app/libs/ctos_print.jar.
         > Transform's input file does not exist: /bitrise/src/app/libs/ctos_print.jar. (See https://issuetracker.google.com/issues/158753935)
![Screenshot 2022-05-23 142949](https://user-images.githubusercontent.com/17463994/169820057-b26eb686-e448-4801-a800-cf8c0805851a.png)

**Comment by ofalvai** [comment]
@abdelrahmana if you continue to experience this issue, I recommend checking out the Google Issue tracker linked in the error message, maybe it's relevant to your project setup. I would also check if this happens locally too, it seems like an issue unrelated to Bitrise and the CI environment.
