### ISSUE TITLE
Android build is failing when updates to compileSDKVersion and targetSDKVersion

### ISSUE THREAD

**Issue by YAsh-Adroja** [bitrise-steplib/bitrise-step-android-build#48]
Hey Guys, 
 
I have faced a problem in making an android build was working perfectly since the last 5 months but my Bitrise workflow is failing when I update compileSDKVersion and targetSDKVersion can you please help me are how to solve this issue 

**Previous** 
- compileSdkVersion : 30
- targetSdkVersion : 30 

Work perfectly 

**Currently**  
- compileSdkVersion : 31
- targetSdkVersion : 31

Can’t work perfectly 

**Screen-short** 

![Screenshot at Aug 24 17-47-51](https://user-images.githubusercontent.com/89472411/186416553-89f3228f-6040-459a-bc4a-cc23fbf2defa.png)
 

Note:- My project is built in React Native framework, On my local system this project works perfectly and successfully created android build 

**System Specification:-**
OS:- Monterey
RAM:- 16 GB
JDK Version:- 11.0.15
React native version:- 0.65.1

**Comment by sufyansalim** [comment]
I am facing kind of similar issue did u managed to fix it ?
